-- Datos de ejemplo para viajes
-- Nota: Estos se insertarán solo si no existen viajes ya creados por usuarios reales

-- Insertar viajes de ejemplo (usando gen_random_uuid() para IDs válidos)
INSERT INTO trips (
    organizer_id, 
    destination, 
    description, 
    start_date, 
    end_date, 
    budget_min, 
    budget_max, 
    max_participants, 
    current_participants,
    room_type, 
    status, 
    tags, 
    image_url, 
    rating, 
    total_ratings, 
    season, 
    country, 
    featured
) 
SELECT 
    -- Usar el primer usuario que encuentre en la base de datos como organizador
    (SELECT user_id FROM user_profiles WHERE identity_verified = true LIMIT 1),
    destination,
    description,
    start_date::date,
    end_date::date,
    budget_min,
    budget_max,
    max_participants,
    current_participants,
    room_type,
    status,
    string_to_array(tags_string, ','), -- Convertir string a array
    image_url,
    rating,
    total_ratings,
    season,
    country,
    featured
FROM (VALUES 
    (
        'Buenos Aires',
        'Viaje cultural explorando la historia y gastronomía porteña. Visitaremos barrios históricos, museos y probaremos el mejor asado.',
        '2024-03-15',
        '2024-03-22',
        800,
        1200,
        8,
        4,
        'both',
        'open',
        'Cultura,Gastronomía,Historia', -- Cambiado a string separado por comas
        '/placeholder.svg?height=200&width=300&text=Buenos Aires',
        4.8,
        15,
        'autumn',
        'Argentina',
        true
    ),
    (
        'Santiago de Chile',
        'Aventura en los Andes chilenos con senderismo, escalada y deportes extremos. Incluye visita a viñedos.',
        '2024-04-05',
        '2024-04-12',
        600,
        900,
        6,
        2,
        'shared',
        'open',
        'Aventura,Naturaleza,Deportes',
        '/placeholder.svg?height=200&width=300&text=Santiago Chile',
        4.9,
        23,
        'autumn',
        'Chile',
        true
    ),
    (
        'Carlos Paz',
        'Relax en las sierras cordobesas con spa, yoga y actividades de bienestar en contacto con la naturaleza.',
        '2024-05-20',
        '2024-05-27',
        500,
        800,
        5,
        3,
        'private',
        'open',
        'Relajación,Bienestar,Naturaleza',
        '/placeholder.svg?height=200&width=300&text=Carlos Paz',
        4.7,
        12,
        'autumn',
        'Argentina',
        false
    ),
    (
        'Montevideo',
        'Descubre la capital uruguaya: ciudad vieja, mercados, playas y la famosa hospitalidad charrúa.',
        '2024-06-10',
        '2024-06-17',
        700,
        1000,
        4,
        1,
        'both',
        'open',
        'Ciudad,Cultura,Playa',
        '/placeholder.svg?height=200&width=300&text=Montevideo',
        4.6,
        8,
        'winter',
        'Uruguay',
        false
    ),
    (
        'Beijing y Shanghai',
        'Viaje épico por China: Gran Muralla, Ciudad Prohibida, Xi''an y Shanghai. Experiencia cultural completa.',
        '2024-08-01',
        '2024-08-15',
        1500,
        2500,
        10,
        6,
        'both',
        'open',
        'Cultura,Historia,Aventura',
        '/placeholder.svg?height=200&width=300&text=Great Wall China',
        4.9,
        31,
        'summer',
        'China',
        true
    ),
    (
        'Bariloche',
        'Aventura en la Patagonia argentina: lagos, montañas y chocolate. Perfecto para amantes de la naturaleza.',
        '2024-09-15',
        '2024-09-22',
        900,
        1400,
        6,
        2,
        'both',
        'open',
        'Naturaleza,Aventura,Montaña',
        '/placeholder.svg?height=200&width=300&text=Bariloche',
        4.8,
        19,
        'spring',
        'Argentina',
        true
    ),
    (
        'Cusco y Machu Picchu',
        'Expedición mística al corazón del imperio inca. Incluye Camino del Inca y conexión espiritual.',
        '2024-10-05',
        '2024-10-12',
        1200,
        1800,
        8,
        3,
        'shared',
        'open',
        'Historia,Cultura,Aventura',
        '/placeholder.svg?height=200&width=300&text=Machu Picchu',
        4.9,
        27,
        'spring',
        'Perú',
        true
    ),
    (
        'Punta del Este',
        'Verano uruguayo en el balneario más exclusivo. Playas, vida nocturna y gastronomía de primer nivel.',
        '2024-12-20',
        '2024-12-27',
        1000,
        1600,
        6,
        1,
        'private',
        'open',
        'Playa,Fiesta,Gastronomía',
        '/placeholder.svg?height=200&width=300&text=Punta del Este',
        4.7,
        14,
        'summer',
        'Uruguay',
        false
    )
) AS sample_trips(
    destination, description, start_date, end_date, budget_min, budget_max,
    max_participants, current_participants, room_type, status, tags_string, 
    image_url, rating, total_ratings, season, country, featured
)
WHERE NOT EXISTS (SELECT 1 FROM trips LIMIT 1); 